# Generated by Django 4.2.29 on 2026-03-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(db_index=True, help_text='外部 ID またはシステム生成 ID', max_length=64, unique=True)),
                ('ja_name', models.CharField(db_index=True, help_text='日本語名', max_length=255)),
                ('en_name', models.CharField(blank=True, help_text='英語名', max_length=255)),
                ('category', models.CharField(choices=[('FINANCIAL_STATEMENT', '財務諸表'), ('KPI', 'KPI'), ('VALUATION', 'バリュエーション'), ('GOVERNANCE', 'コーポレートガバナンス'), ('MA', 'M&A'), ('ESG', 'ESG・サステナビリティ'), ('CONSULTING', '経営コンサルティング'), ('RISK', 'リスク管理'), ('ACCOUNTING', '会計・税務'), ('IR', 'IR・投資家'), ('HUMAN_CAPITAL', '人的資本'), ('STRATEGY', '経営戦略'), ('OTHER', 'その他')], default='OTHER', max_length=32)),
                ('source', models.CharField(blank=True, help_text='取り込み元ファイル名', max_length=128)),
                ('description', models.TextField(blank=True, help_text='補足説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用語集',
                'verbose_name_plural': '用語集一覧',
                'ordering': ['ja_name'],
            },
        ),
    ]
